export enum VerificationStatus {
  VALID = 'VALID',
  INVALID = 'INVALID',
  ALREADY_USED = 'ALREADY_USED',
  CANCELLED = 'CANCELLED',
  EVENT_NOT_STARTED = 'EVENT_NOT_STARTED',
  EVENT_ENDED = 'EVENT_ENDED',
}